version: "3.8"

services:
  localstack:
    container_name: "netwatch-local-aws"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,apigateway,dynamodb,s3,sns,eventbridge
      - DEBUG=1